FROM        tianon/exim4
MAINTAINER  Paul R. Tagliamonte <paultag@debian.org>
ADD         01_exim4-config_listmacrosdefs /etc/exim4/conf.d/main/
ADD         350_exim4-config_vdom_aliases  /etc/exim4/conf.d/main/
