#!/bin/sh
# Copyright (c) Paul R. Tagliamonte 2014, MIT/Expat

if [ ! -d /dev/net ]; then
    mkdir -p /dev/net
fi

if [ ! -c /dev/net/tun ]; then
    mknod /dev/net/tun c 10 200
fi

chown -R root:root /etc/openvpn/*
chmod 600 /etc/openvpn/*


exec /usr/sbin/openvpn \
    --cd /etc/openvpn \
    --config /etc/openvpn/server.conf
