#!/bin/bash
# Copyright (c) Paul R. Tagliamonte, MIT/Expat
set -e

VERSION="9.4"  # XXX: Update this with the rest of the dockerfiles.
DATABASEDIR="/var/lib/postgresql/${VERSION}/main"

DB_OWNER=$(stat -c "%U" ${DATABASEDIR})

if [ "x${DB_OWNER}" != "xpostgres" ]; then
    chown -R postgres:postgres ${DATABASEDIR}
fi

chmod 0700 ${DATABASEDIR}

if [ ! -e "${DATABASEDIR}/PG_VERSION" ]; then
    PW_FILE=$(mktemp)
    echo "postgres" > ${PW_FILE}
    chmod 666 ${PW_FILE}  # \m/

    # We need to set up the DB before we kickoff.
    su -l postgres -c \
        "/usr/lib/postgresql/${VERSION}/bin/initdb --pwfile=${PW_FILE} -D ${DATABASEDIR}"

    rm ${PW_FILE}
fi

exec sudo -u postgres \
    /usr/lib/postgresql/${VERSION}/bin/postgres \
        -D ${DATABASEDIR} \
        -c config_file=/etc/postgresql/${VERSION}/main/postgresql.conf
