#!/bin/bash
# Copyright (c) Paul R. Tagliamonte, MIT/Expat

VERSION="9.3"  # XXX: Update this with the rest of the dockerfiles.
DATABASEDIR="/var/lib/postgresql/${VERSION}/main"


if [ ! -d ${DATABASEDIR} ]; then
    # We need to set up the DB before we kickoff.
    pg_ctl initdb -D ${DATABASEDIR}
fi

exec /usr/lib/postgresql/${VERSION}/bin/postgres \
        -D ${DATABASEDIR} \
        -c "config_file=/etc/postgresql/${VERSION}/main/postgresql.conf"
