#!/bin/bash
# Copyright (c) Paul R. Tagliamonte, MIT/Expat

VERSION="9.3"  # XXX: Update this with the rest of the dockerfiles.
DATABASEDIR="/var/lib/postgresql/${VERSION}/main"

DB_OWNER=$(stat -c "%U" ${DATABASEDIR})

if [ "x${DB_OWNER}" != "xpostgres" ]; then
    chown -R postgres:postgres ${DATABASEDIR}
fi

chmod 0700 ${DATABASEDIR}

if [ ! -e "${DATABASEDIR}/PG_VERSION" ]; then
    # We need to set up the DB before we kickoff.
    /usr/lib/postgresql/${VERSION}/bin/initdb \
        -D ${DATABASEDIR}
fi

exec su -l postgres -c "
    /usr/lib/postgresql/${VERSION}/bin/postgres \
        -D ${DATABASEDIR} \
        -c config_file=/etc/postgresql/${VERSION}/main/postgresql.conf"
